### ISSUE TITLE
Пустой позывной

### ISSUE THREAD

**Issue by R3LO** [VK6NX/OCLog-v1.x#1]
В лог вносится пустая связь если поле CALL пустое

**Comment by VK6NX** [comment]
Уже поправлено в новой версии. Пока сделана активация кнопки записи есть в call внесен хотя бы один знак. Если этого будет недостаточно - увеличу до 3х знаков.

Следующую версию с поправками выложу в субботу 1 октября.

**Comment by VK6NX** [comment]
Поправлено в опубликованном 1.3
