### ISSUE TITLE
How to customize the sent exchange?

### ISSUE THREAD

**Issue by tudor-v** [VK6NX/OCLog-v1.x#2]
Hello,

Just found this log app and it might be perfect for me, as I'm a beginner in ham radio contesting and I don't need a full featured logging app. Just something simple and compatible with my SunSDR DX.

One question though: can I customize the sent exchange to something like this: 
`<RS><serial number><some letters>`

Example: 59001AB, 59002AB, 59003AB etc.

Thank you!

**Comment by VK6NX** [comment]
I have added automatic RS<->RST switch dependent on mode:
- If CW mode is selected in ESDR3 - RSTsend and RSTrcvd fields are pre-populated with 5NN
- if any other mode is selected in ESDR3 - RSTsend and RSTrcvd fields are pre-populated with 59

Assuming my understanding is correct and in your example 59001AB is as following:
59 = RS
001 = STX (as per [ADIF](https://adif.org/313/ADIF_313.htm) STX is contest QSO transmitted serial number)
AB = STX_STRING (as per same document STX_STRING is contest QSO transmitted information

then, you can configure it - when Contest mode is selected - in OClog Settings (latest build v1.3.1 update 1):
[https://github.com/VK6NX/OCLog-v1.x/blob/main/images/oclog_u1.jpg](url)

**if Contest is required STX_STRING** and you are in any (USB/LSB, etc) mode **except CW**
- tick Contest STX info enables configurable STX_STRING (which also shows at dash panel)
- tick Contest SRX info enables SRX_STRING field on dash (for manuall filling with received data from correspondent) 
Both fields data will be written into corresponding ADIF record.

Also in Contest mode the
- SRX (the received QSO serial number) is always enabled - this is manually filled from the sequence number received from the corrspondent
- STX is automatically filled with the next QSO sequence number, started with '1', when log is empty. That is why it is recommended to export/clean-up the log before every new contest: the STX is automatically calculated from non-exported (logged) QSO numbers which are currently in the Log. Hence, if you have a break during Contest, just continue when you return - the next QSO number will be recorded.

In addition to above, **when in Contest and CW mode**:
STX and STX_STRING are also subject to automation via CW macro. For example the following macro sequence:
_${RCVCALL} ${SNDRST} ${STX} ${STXSTR}_
will be transmitted as (for example) _VK6NX 5NN 001 AB_
Where VK6NX is a call sign
5NN is RST you are sending
001 is STX (yours Contest QSO sequence number)
AB is STX_STRING (yours Contest additinal info)

Hope that explains

**Comment by VK6NX** [comment]
pehraps, there are no further questions; I convert this one into discussion.
